services:
    main:
        container_name: main
        build: 
            context: .
        env_file:
            - .prod.env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
        command: npm run start
        depends_on:
            - mongodb
        restart: always

    mongodb:
        container_name: mongo
        ports:
            - '27017:27017'
        image: mongo:latest
        restart: always
        volumes:
            - mongodb:/data/db

volumes:
    mongodb: {}