services:
    main:
        container_name: main
        build: 
            context: .
        env_file:
            - .prod.env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 80:80
        command: npm run start
        depends_on:
            - mongodb
        restart: always

    mongodb:
        container_name: mongo
        ports:
            - '27017:27017'
        image: mongo:latest
        restart: always
        volumes:
            - mongodb:/data/db

    redis:
        image: "redis:alpine"
        command: redis-server
        expose:
        - "6379"
        volumes:
        - redis-data:/data
        - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
    mongodb:
    redis-data:
    redis-conf: